class ServerModel {
  final String id;
  final String name;
  final String country;
  final String countryAr;
  final String city;
  final String flag;
  final String fileName;
  final String rawUrl;
  final String ip;
  final int ping;
  bool isPremium;
  bool isFavorite;

  ServerModel({
    required this.id,
    required this.name,
    required this.country,
    required this.countryAr,
    required this.city,
    required this.flag,
    required this.fileName,
    required this.rawUrl,
    required this.ip,
    this.ping = 0,
    this.isPremium = false,
    this.isFavorite = false,
  });

  factory ServerModel.fromJson(Map<String, dynamic> json) {
    return ServerModel(
      id: json['id'],
      name: json['name'],
      country: json['country'],
      countryAr: json['countryAr'],
      city: json['city'],
      flag: json['flag'],
      fileName: json['fileName'],
      rawUrl: json['rawUrl'],
      ip: json['ip'],
      ping: json['ping'] ?? 0,
      isPremium: json['isPremium'] ?? false,
      isFavorite: json['isFavorite'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'country': country,
      'countryAr': countryAr,
      'city': city,
      'flag': flag,
      'fileName': fileName,
      'rawUrl': rawUrl,
      'ip': ip,
      'ping': ping,
      'isPremium': isPremium,
      'isFavorite': isFavorite,
    };
  }
}

// All 33 servers from the GitHub repository
final List<ServerModel> allServers = [
  ServerModel(
    id: 'dz',
    name: 'Algeria',
    country: 'Algeria',
    countryAr: 'الجزائر',
    city: 'Algiers',
    flag: '🇩🇿',
    fileName: 'Algeria_PIA_154.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Algeria_PIA_154.ovpn',
    ip: '154.0.0.0',
  ),
  ServerModel(
    id: 'bh',
    name: 'Bahrain',
    country: 'Bahrain',
    countryAr: 'البحرين',
    city: 'Manama',
    flag: '🇧🇭',
    fileName: 'Bahrain_-_Manama_388.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Bahrain_-_Manama_388.ovpn',
    ip: '188.0.0.0',
  ),
  ServerModel(
    id: 'br',
    name: 'Brazil',
    country: 'Brazil',
    countryAr: 'البرازيل',
    city: 'São Paulo',
    flag: '🇧🇷',
    fileName: 'Brazil_PIA_169.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Brazil_PIA_169.ovpn',
    ip: '169.0.0.0',
  ),
  ServerModel(
    id: 'ca',
    name: 'Canada',
    country: 'Canada',
    countryAr: 'كندا',
    city: 'Montreal',
    flag: '🇨🇦',
    fileName: 'Canada_-_Montreal_PIA_171.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Canada_-_Montreal_PIA_171.ovpn',
    ip: '171.0.0.0',
  ),
  ServerModel(
    id: 'cn',
    name: 'China',
    country: 'China',
    countryAr: 'الصين',
    city: 'Beijing',
    flag: '🇨🇳',
    fileName: 'China_PIA_177.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/China_PIA_177.ovpn',
    ip: '177.0.0.0',
  ),
  ServerModel(
    id: 'cy',
    name: 'Cyprus',
    country: 'Cyprus',
    countryAr: 'قبرص',
    city: 'Nicosia',
    flag: '🇨🇾',
    fileName: 'Cyprus_PIA_181.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Cyprus_PIA_181.ovpn',
    ip: '181.0.0.0',
  ),
  ServerModel(
    id: 'eg',
    name: 'Egypt',
    country: 'Egypt',
    countryAr: 'مصر',
    city: 'Cairo',
    flag: '🇪🇬',
    fileName: 'Egypt_PIA_187.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Egypt_PIA_187.ovpn',
    ip: '187.0.0.0',
  ),
  ServerModel(
    id: 'fr',
    name: 'France',
    country: 'France',
    countryAr: 'فرنسا',
    city: 'Paris',
    flag: '🇫🇷',
    fileName: 'France_PIA_192.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/France_PIA_192.ovpn',
    ip: '192.0.0.0',
  ),
  ServerModel(
    id: 'in',
    name: 'India',
    country: 'India',
    countryAr: 'الهند',
    city: 'Mumbai',
    flag: '🇮🇳',
    fileName: 'India_PIA_200.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/India_PIA_200.ovpn',
    ip: '200.0.0.0',
  ),
  ServerModel(
    id: 'il',
    name: 'Israel',
    country: 'Israel',
    countryAr: 'إسرائيل',
    city: 'Tel Aviv',
    flag: '🇮🇱',
    fileName: 'Israel_PIA_204.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Israel_PIA_204.ovpn',
    ip: '204.0.0.0',
  ),
  ServerModel(
    id: 'jp',
    name: 'Japan',
    country: 'Japan',
    countryAr: 'اليابان',
    city: 'Tokyo',
    flag: '🇯🇵',
    fileName: 'Japan_-_Tokyo_442.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Japan_-_Tokyo_442.ovpn',
    ip: '142.0.0.0',
  ),
  ServerModel(
    id: 'ma',
    name: 'Morocco',
    country: 'Morocco',
    countryAr: 'المغرب',
    city: 'Casablanca',
    flag: '🇲🇦',
    fileName: 'Morocco_PIA_220.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Morocco_PIA_220.ovpn',
    ip: '105.196.14.201',
  ),
  ServerModel(
    id: 'nl',
    name: 'Netherlands',
    country: 'Netherlands',
    countryAr: 'هولندا',
    city: 'Amsterdam',
    flag: '🇳🇱',
    fileName: 'Netherlands_-_Amsterdam_424.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Netherlands_-_Amsterdam_424.ovpn',
    ip: '185.0.0.0',
  ),
  ServerModel(
    id: 'pl',
    name: 'Poland',
    country: 'Poland',
    countryAr: 'بولندا',
    city: 'Warsaw',
    flag: '🇵🇱',
    fileName: 'Poland_-_Warsaw_426.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Poland_-_Warsaw_426.ovpn',
    ip: '194.0.0.0',
  ),
  ServerModel(
    id: 'pt',
    name: 'Portugal',
    country: 'Portugal',
    countryAr: 'البرتغال',
    city: 'Lisbon',
    flag: '🇵🇹',
    fileName: 'Portugal_-_Lisbon_427.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Portugal_-_Lisbon_427.ovpn',
    ip: '188.0.0.0',
  ),
  ServerModel(
    id: 'qa',
    name: 'Qatar',
    country: 'Qatar',
    countryAr: 'قطر',
    city: 'Doha',
    flag: '🇶🇦',
    fileName: 'Qatar_PIA_232.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Qatar_PIA_232.ovpn',
    ip: '178.0.0.0',
  ),
  ServerModel(
    id: 'sa',
    name: 'Saudi Arabia',
    country: 'Saudi Arabia',
    countryAr: 'السعودية',
    city: 'Riyadh',
    flag: '🇸🇦',
    fileName: 'Saudi_Arabia_PIA_234.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Saudi_Arabia_PIA_234.ovpn',
    ip: '51.0.0.0',
  ),
  ServerModel(
    id: 'sg',
    name: 'Singapore',
    country: 'Singapore',
    countryAr: 'سنغافورة',
    city: 'Singapore',
    flag: '🇸🇬',
    fileName: 'Singapore_-_Singapore_445.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Singapore_-_Singapore_445.ovpn',
    ip: '103.0.0.0',
  ),
  ServerModel(
    id: 'za1',
    name: 'South Africa',
    country: 'South Africa',
    countryAr: 'جنوب أفريقيا',
    city: 'Johannesburg',
    flag: '🇿🇦',
    fileName: 'South_Africa_-_Johannesburg_451.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/South_Africa_-_Johannesburg_451.ovpn',
    ip: '102.0.0.0',
  ),
  ServerModel(
    id: 'za2',
    name: 'South Africa 2',
    country: 'South Africa',
    countryAr: 'جنوب أفريقيا 2',
    city: 'Cape Town',
    flag: '🇿🇦',
    fileName: 'South_Africa_PIA_240.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/South_Africa_PIA_240.ovpn',
    ip: '197.0.0.0',
  ),
  ServerModel(
    id: 'kr1',
    name: 'South Korea',
    country: 'South Korea',
    countryAr: 'كوريا الجنوبية',
    city: 'Seoul',
    flag: '🇰🇷',
    fileName: 'South_Korea_-_Seoul_443.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/South_Korea_-_Seoul_443.ovpn',
    ip: '221.0.0.0',
  ),
  ServerModel(
    id: 'kr2',
    name: 'South Korea 2',
    country: 'South Korea',
    countryAr: 'كوريا الجنوبية 2',
    city: 'Busan',
    flag: '🇰🇷',
    fileName: 'South_Korea_PIA_241.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/South_Korea_PIA_241.ovpn',
    ip: '211.0.0.0',
  ),
  ServerModel(
    id: 'es',
    name: 'Spain',
    country: 'Spain',
    countryAr: 'إسبانيا',
    city: 'Madrid',
    flag: '🇪🇸',
    fileName: 'Spain_-_Madrid_432.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Spain_-_Madrid_432.ovpn',
    ip: '185.0.0.0',
  ),
  ServerModel(
    id: 'ch',
    name: 'Switzerland',
    country: 'Switzerland',
    countryAr: 'سويسرا',
    city: 'Zurich',
    flag: '🇨🇭',
    fileName: 'Switzerland_-_Zurich_434.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Switzerland_-_Zurich_434.ovpn',
    ip: '194.0.0.0',
  ),
  ServerModel(
    id: 'tr1',
    name: 'Turkey',
    country: 'Turkey',
    countryAr: 'تركيا',
    city: 'Istanbul',
    flag: '🇹🇷',
    fileName: 'Turkey_-_Istanbul_435.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Turkey_-_Istanbul_435.ovpn',
    ip: '212.0.0.0',
  ),
  ServerModel(
    id: 'tr2',
    name: 'Turkey 2',
    country: 'Turkey',
    countryAr: 'تركيا 2',
    city: 'Ankara',
    flag: '🇹🇷',
    fileName: 'Turkey_PIA_245.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Turkey_PIA_245.ovpn',
    ip: '195.0.0.0',
  ),
  ServerModel(
    id: 'ae',
    name: 'UAE',
    country: 'UAE',
    countryAr: 'الإمارات',
    city: 'Dubai',
    flag: '🇦🇪',
    fileName: 'UAE_PIA_250.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/UAE_PIA_250.ovpn',
    ip: '94.0.0.0',
  ),
  ServerModel(
    id: 'ua',
    name: 'Ukraine',
    country: 'Ukraine',
    countryAr: 'أوكرانيا',
    city: 'Kyiv',
    flag: '🇺🇦',
    fileName: 'Ukraine_-_Kyiv_436.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/Ukraine_-_Kyiv_436.ovpn',
    ip: '176.0.0.0',
  ),
  ServerModel(
    id: 'gb',
    name: 'United Kingdom',
    country: 'United Kingdom',
    countryAr: 'المملكة المتحدة',
    city: 'London',
    flag: '🇬🇧',
    fileName: 'United_Kingdom_-_London_438.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/United_Kingdom_-_London_438.ovpn',
    ip: '185.0.0.0',
  ),
  ServerModel(
    id: 'us1',
    name: 'United States',
    country: 'United States',
    countryAr: 'الولايات المتحدة',
    city: 'New Jersey',
    flag: '🇺🇸',
    fileName: 'United_States_-_New_Jersey_403.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/United_States_-_New_Jersey_403.ovpn',
    ip: '198.0.0.0',
  ),
  ServerModel(
    id: 'us2',
    name: 'United States 2',
    country: 'United States',
    countryAr: 'الولايات المتحدة 2',
    city: 'South Dakota',
    flag: '🇺🇸',
    fileName: 'United_States_-_South_Dakota_PIA_294.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/United_States_-_South_Dakota_PIA_294.ovpn',
    ip: '174.0.0.0',
  ),
  ServerModel(
    id: 'us3',
    name: 'United States 3',
    country: 'United States',
    countryAr: 'الولايات المتحدة 3',
    city: 'Texas',
    flag: '🇺🇸',
    fileName: 'United_States_-_Texas_PIA_296.ovpn',
    rawUrl: 'https://raw.githubusercontent.com/mx711k7-dot/prx/refs/heads/main/United_States_-_Texas_PIA_296.ovpn',
    ip: '184.0.0.0',
  ),
];
